### PR TITLE
PIP-964||HEP-913|916|946|956: SynthEyes: Bug-Fixes & Improvements

### PR DESCRIPTION
**Pull request by dzohlen**
Features:
- HEP-913: Added extra check to prevent potential race condition between SynthEyes and SG
- HEP-916: Added some extra checks to prevent blocking user interactions
- PIP-964/HEP-946: Reduced path length for distortion map-publishes
- Message boxes now appear on the center of the screen instead of being centered on their parent
- Adjusted export presets for publishes based on feedback
- HEP-956: Match frame numbers for Undistorted Plate & Playblast to shot settings in SynthEyes (_Shot → Edit Shot_)

Repositories:
- tk-config-lavapipeline: https://github.com/lavalmi/tk-config-lavapipeline/pull/154
- tk-framework-lavapipeline: https://github.com/lavalmi/tk-framework-lavapipeline/pull/43
- tk-framework-ll_scenetasks_prototype: https://github.com/lavalmi/tk-framework-ll_scenetasks_prototype/pull/35

Dev Config:
- Engines:
-- tk-syntheyes
- Frameworks:
-- tk-framework-lavapipeline
-- tk-framework-ll_scenetasks_prototype

Environment:
- Project: matchmove_dev
- Test scene: **Shots** → **Sequence** 010 → **Shot** 010_010 → **Step** MM → **Task** mm → SimpleTestScene.v044.sni
- SynthEyes Pro 2024 Build 1057 64-bit installed at "C:\Program Files\BorisFX\SynthEyes 2024\SynthEyes64.exe"
- SynthEyes: Default port range from 59200-59300
- Shotgun python version: 3.7.11

### CODE REVIEW

**Review by vike41 — CHANGES_REQUESTED** [review]
Hi Damian, 
One thing that seemed strange in the workflow is the pop-up window. When SynthEyes presents a dialog window, this window (see screenshot) does not allow for it to be closed. Because synthEye window can be hidden behind publish window. If you can, please take another look at this issue.
grafik

**Comment by dzohlen** [comment]
> Hi Damian, One thing that seemed strange in the workflow is the pop-up window. When SynthEyes presents a dialog window, this window (see screenshot) does not allow for it to be closed. Because synthEye window can be hidden behind publish window. If you can, please take another look at this issue. grafik

I made some changes to the logic when asking the user to close all open popups: The UI is now fully minimized except for the message box itself. Once the ok-button is clicked and all popups are closed, the UI reappears by itself. During testing, this worked fine for me with the popups I was able to test it on.
Hopefully, this resolves this issue properly as I was not able to make SynthEyes open that exact popup.

**Review by vike41 — APPROVED** [review]
Good Job! Really good. Don't forget to remove unused import at export files at refactoring phase. Vitalii

**Comment by vike41** [comment]
@JanPhKoch, to run it u need:
tk-syntheyes: syntheyes-devel
tk-framework-ll_scenetasks_prototype: `HEP-916_syntheyes_locked_ui`
tk-confing-lavapipeline: u need merged dev/syntheyes and right config. 
grafik

**Review by JanPhKoch — APPROVED** [review]

**Pull request merged**
